import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {IdentityProvider} from './AuthorContext/IdentityContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Buy Me All',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"><IdentityProvider>
      <body className={inter.className}>{children}</body></IdentityProvider>
    </html>
  )
}
